import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import providerRoutes from './routes/providerRoutes.js';
import appointmentRoutes from './routes/appointmentRoutes.js';
dotenv.config();
const app = express();
app.use(cors({origin:'*'}));
app.use(express.json());
connectDB();
app.use('/api/auth',authRoutes);
app.use('/api/providers',providerRoutes);
app.use('/api/appointments',appointmentRoutes);
app.listen(process.env.PORT||5000);